version: 2
jobs:
    test:
        working_directory: ~/repo
        context: test
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: npm run test

    build:
        working_directory: ~/repo
        context: test
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: npm run build

workflows:
    version: 2
    fun_and_games:
        jobs:
            - build
            - test
